server:
  port: 8085

spring:
  application:
    name: api-gateway
  security:
    user:
      name: Gandalf
      password: Scadufax2002
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8080
          predicates:
            - Path=/book-service/v1/**
        - id: order-service
          uri: http://localhost:8088
          predicates:
            - Path=/order-service/v1/**
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/payment-service/v1/**
        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/cart-service/v1/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/v1/**
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/notification-service/v1/**
